### ISSUE TITLE
Projects can have more than one Bukkit project type assigned to it

### ISSUE THREAD

**Issue by DemonWav** [DemonWav/MinecraftDev#54]
If a project changes it's dependencies then in some cases it seems the original Bukkit-type isn't removed, while the second Bukkit-type is also added on (so, it could be both a `BukkitModuleType` and a `SpigotModuleType`). This shouldn't happen, only the highest Bukkit-type should remain.

**Comment by JBYoshi** [comment]
@DemonWav It could also happen if someone depends on multiple Bukkit dependencies (e.g. Bukkit and Spigot) at the same time.
