### ISSUE TITLE
2016.3 EAP - Found interface but class was expected

### ISSUE THREAD

**Issue by Meronat** [DemonWav/MinecraftDev#66]
I'm not sure if you're interested in bugs in EAP, but just in-case, this bug was called an IDE Fatal Error using the latest version of the 2016.3 EAP(build 163.4830.24).

The error message was: Found interface org.jetbrains.concurrency.Promise, but class was expected

The stack trace was: 
![stacktrace](https://cloud.githubusercontent.com/assets/18372958/18817843/97f5c75a-8330-11e6-9bda-66f11913132f.PNG)

**Comment by DemonWav** [comment]
This is due to a change in 2016.3 where Promise went from an abstract class to an interface. Rebuilding against 2016.3 fixes it. I'll see about pushing a fix out into the EAP channel for you.

@me4502

**Comment by DemonWav** [comment]
Update to the latest version of the plugin, then change your update channel to EAP. (Ctrl-Shift-A, Configure Minecraft Development Plugin Updates).

**Comment by DemonWav** [comment]
IntelliJ is really stupid, so it looks like you'll have to change your channel, the uninstall and reinstall the plugin. I'll try to fix it, but it has to do with how it reads the version strings. It think alpha-0.2.6-eap is a lower version than alpha-0.2.6 for some reason, then refuses to update it. So you have to work around it a bit. Changing the update channel will survive the plugin uninstall and reinstall.

**Comment by DemonWav** [comment]
Let me know if this is still an issue.

**Comment by Meronat** [comment]
@DemonWav Okay so, I switched over to alpha-0.2.7-eap and a multitude of errors popped up, at least when creating a new Minecraft Dev Sponge project.

**This is using the latest version of the 2016.3 EAP:**
IntelliJ IDEA (Community Edition) 2016.3 EAP
Build #IC-163.5219.11, built on September 27, 2016
JRE: 1.8.0_122-ea-b01 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**1** - Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details. http://pastebin.com/LUMKDN5f

**2** - Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details. http://pastebin.com/ZYgrCGkg

**3** - Cannot run synchronous submitTransactionAndWait from invokeLater. Please use asynchronous submit*Transaction. See TransactionGuard FAQ for details. http://pastebin.com/KphhSATa

**4** - Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'. http://pastebin.com/s8nbifep

**Comment by DemonWav** [comment]
Looks like they made quite a few changes to how they handle threading in 2016.3. This will be more complicated to fix than just recompiling. :)

**Comment by DemonWav** [comment]
Alright, see if that fixed it.

**Comment by Meronat** [comment]
I updated to the latest version, with the EAP channel selected, but it seems to have installed alpha-0.2.10 and I had 9 errors this time. Sorry I've been such a hassle though, thanks for doing a great job with this plugin.

**IntelliJ IDEA Specs:**

IntelliJ IDEA (Community Edition) 2016.3 EAP
Build #IC-163.5219.11, built on September 27, 2016
JRE: 1.8.0_122-ea-b01 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Message followed by stack trace on pastebin:**

**1.** null - http://pastebin.com/G4icQc8d

**2.** null - http://pastebin.com/HnuNaUkd

**3.** null - http://pastebin.com/AkuUHvvR

**4.** Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details. - http://pastebin.com/sWi5C5Jg

**5.** Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details. - http://pastebin.com/eLgZMxe5

**6.** Write access is allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details. - http://pastebin.com/UamASsYg

**7.** Cannot run synchronous submitTransactionAndWait from invokeLater. Please use asynchronous submit*Transaction. See TransactionGuard FAQ for details. - http://pastebin.com/rHPQTFDn

**8.** Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-bin.zip'. - http://pastebin.com/4a8cZVSb

**9.** null - http://pastebin.com/cDZfAjug

**Comment by DemonWav** [comment]
Hmm, did I not push the last update or something? I definitely fixed at the very least number 8 haha. Sorry about these issues.

**Comment by DemonWav** [comment]
Oh, yeah, you have to uninstall alpha-0.2.10 and reinstall the plugin to get alpha-0.2.10-eap. It's an IntelliJ issue I need to figure out how to work around.

**Comment by Meronat** [comment]
@DemonWav Oh yeah sorry I forgot to do that this time, it seems to have worked for now, I'll keep you updated. Thank you so much.
