### ISSUE TITLE
SpongeAPI submodule needs Spongie favicon

### ISSUE THREAD

**Issue by Zidane** [DemonWav/MinecraftDev#71]

**Comment by DemonWav** [comment]
Does this mean you installed the plugin?

**Comment by Zidane** [comment]
Yes,.....nope.

Your image in -dev showed SpongeAPI with no icon LOL.

**Comment by JBYoshi** [comment]
Actually, why not do this for all platforms? As in, if the module depends on a certain API, *or if it is that API itself*, then make it that module type.

**Comment by Zidane** [comment]
Um, I don't care about those @JBYoshi 

SpongeAPI doesn't have Sponge icon. Simple as that.

**Comment by DemonWav** [comment]
If I make this change it will be for all platforms. Currently it only is valid if the module depends on the API, but never for any platform if the module itself is the API. That's a pretty simple thing to add to allow it to work for the module if it is itself the API.

**Comment by DemonWav** [comment]
Fixed in f6b0ec3.
