### ISSUE TITLE
No support for creating Forge 1.7.10 / 1.8

### ISSUE THREAD

**Issue by TehNeon** [DemonWav/MinecraftDev#76]
There is currently now way to create a Forge mod from the menu for 1.7.10 or just 1.8, and it would be nice if it was possible to do this.

**Comment by DemonWav** [comment]
There was a reason I did this, but I don't remember why. No promises, but I'll look into seeing if I can figure out why I made that decision and I'll reply back here with more details.

**Comment by kinggoesgaming** [comment]
If LexManos saw this request xD

**Comment by kashike** [comment]
Reasoning is that we don't want to support *ancient* versions of Minecraft.
Additionally, it would be a lot of work to support Forge for 1.7.10 and below.

**Comment by jamierocks** [comment]
Unfortunately people do still use Forge 1.7.10, it would be a shame to alienate them.

**I am not saying I condone people using Forge 1.7.10**

**Comment by TehNeon** [comment]
Originally what kashike said about not wanting to support ancient version of Minecraft. I thought about this but what jamierocks said is that many people still use Forge 1.7.10. I just had this as a suggestion, and it's just more of an inconvenience to have the project creator to not have it auto setup.

**Comment by DemonWav** [comment]
There's several things that make supporting the older versions a headache for me, and it's not very difficult to set them manually. I also don't want to encourage people to use and write code for older versions.
