### ISSUE TITLE
Forge static event listeners not detected

### ISSUE THREAD

**Issue by Katrix-** [DemonWav/MinecraftDev#77]
Forge has static event listeners that can be registered as classes instead of instances. It would be nice if these were properly detected. The only change is that the method is static, and when registering the listener, you provide the class instead of an instance.

**Comment by kashike** [comment]
https://github.com/DemonWav/MinecraftDev/issues/43

**Comment by DemonWav** [comment]
Not a duplicate. @Katrix- is talking about event listener detection.
