### ISSUE TITLE
Require entities to have constructor taking only world

### ISSUE THREAD

**Issue by Katrix-** [DemonWav/MinecraftDev#79]
In forge all entities are required to have a constructor that takes just a World, nothing else. If it doesn't Minecraft will fail to instantiate that entity.

My suggestion is simply to have a inspection to make sure that constructor exists.

**Comment by DemonWav** [comment]
Isn't this already handled by the fact the subclass must have a constructor to match the super class? Or can you create entities without extending Entity?

**Comment by kashike** [comment]
Not all entities just have a constructor which accepts `World`, they can have ones which also take a position (x, y, z), `BlockPos`, "thrower", etc. A mod entity can add that constructor, but forget to add a constructor with a single `World` as well.
